--- #YAML:1.0
name:               Dancer-Plugin-Auth
version:            0.2
abstract:           systeme authentication for Dancer applications.
author:
    - Natal Ngétal <hobbestig@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:               1.175
    Dancer::Plugin::DBIC:  0
    Digest::SHA:          0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
